[package]
name = "snake"
version = "0.1.0"
authors = ["Grzegorz <grzegorz.bartoszek@thaumatec.com>"]
edition = "2021"

[dependencies]
derive-new = "0.5"
paste = "0.1"

[features]
default = ["std"]
std = []
