[package]
name = "snake-quicksilver"
version = "0.1.0"
authors = ["Grzegorz <grzegorz.bartoszek@thaumatec.com>"]
edition = "2018"

[dependencies]
quicksilver = "*"
snake = { path = "../snake-core" }
rand = "0.6.5"
paste = "0.1"
